### PR TITLE
fix: remove Dependency Dashboard

### LINKED ISSUE #30: Dependency Dashboard
This issue provides visibility into Renovate updates and their statuses. [Learn more](https://docs.renovatebot.com/key-concepts/dashboard/)

This repository currently has no open or pending branches.

---

- [ ] Check this box to trigger a request for Renovate to run again on this repository

### PR DESCRIPTION
**Pull request by dirien**
fixes #30 

Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

The dashboard is not useful, on most project have it disabled.

### CODE REVIEW

**Comment by brumhard** [comment]
I kinda like it tbh. @linuxluigi what do you think?

**Comment by linuxluigi** [comment]
Honestly I'm not sure if it can be useful or not. I think we should at first enable renovatebot on this repo to test it. Afterwards we can disable it, if it's not an help.

**Comment by brumhard** [comment]
Well actually it is already enabled, we just don't have many dependencies on this project so the PRs don't come in too frequently. But maybe that's also a good reason to not go with the dashboard, since it's more or less only useful if we have a lot of renovatebot action.

**Comment by brumhard** [comment]
@linuxluigi I'd be ok with disabling it to get rid of the issue in our board and re-enable it if we ever feel the need for it.

**Review by linuxluigi — APPROVED** [review]

**Comment by linuxluigi** [comment]
Alright, you are right. I didn't saw I before, but your right. It is not that useful 😅

**Pull request merged**
