### PR TITLE
feat: add goreleaser for gt cli

### LINKED ISSUE #45: feat: add goreleaser for gt cli
Hi everyone,

I would like to contribute the [goreleaser](https://goreleaser.com/) support for gt. 

Discussion under -> https://github.com/SchwarzIT/go-template/discussions/43

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

fixes #45 

As discussed in https://github.com/SchwarzIT/go-template/discussions/43 the PR for gt itself.

### CODE REVIEW

**Comment by dirien** [comment]
@brumhard: Added  the install notes for the intstalltion of the binaries.

The question with the version: I did not understand 😅. In goreleaser you can pass the version being released to the LDFLAGS -x.

As you saw from the PR, i did not touched this area, and the version will still be collected from the txt file.

**Comment by brumhard** [comment]
Ty 🙏 
Well my only point is that now 2 values in the version output (commit and date) are set during build but the version on the other hand is set in a file.
The reason for using the file was that you could use `go install` without the special build flags to get the same Version output as with any prebuilt binary.
With the additions of commit and date this is not possible anymore (since they need to be set through build flags). Now the question is do we really need the newly.added information or could we just go with the version tag which also clearly communicates the tag and therefore the commit and date implicitly in the git history. I think I would prefer that to keep `go install` working.

**Comment by dirien** [comment]
@brumhard, ofc i can drop them from the PR. Just let me know, and I remove the two -X from the goreleaser and delte the variables from the `versions.go`

**Comment by brumhard** [comment]
@dirien alright then lets keep them out of the PR for now and we can still add them later if we feel the need for it 👍

**Comment by dirien** [comment]
@brumhard done and gone :)

**Comment by dirien** [comment]
@brumhard, Thanks! 

if you plan to create a release let me know so I can be around. THE GITHUB_TOKEN should automatically set. But you never know 😄

**Pull request merged**
