### PR TITLE
fix(template): Set versioncontrol from golangci via go.mod

### PR DESCRIPTION
**Pull request by linuxluigi**
Set versioncontrol from golangci via go.mod

### CODE REVIEW

**Comment by linuxluigi** [comment]
I'm not sure if this is a great idea... 
https://golangci-lint.run/usage/install/#install-from-source

Screenshot 2023-02-13 at 15 55 40

**Comment by brumhard** [comment]
Well to be honest I didn't have any issues with it in the past half year. So i would consider it fairly stable. If some version breaks you can still pin it for a while.

**Comment by linuxluigi** [comment]
I run in an issue instantly after migrating it 😂
But for me is the workflow still okay.

**Review by brumhard — DISMISSED** [review]
LGTM. I think we might want to migrate the other tools to this workflow as well (especially the grpc ones) but we can do it in another PR.

**Comment by linuxluigi** [comment]
Yeah good idea, I try to create a PR soon for that 🙂

**Review by brumhard — APPROVED** [review]

**Pull request merged**
