### PR TITLE
fix(ci): Remove RenovateBot

### PR DESCRIPTION
**Pull request by johannes-riecken**
We'd prefer to use Github's integrated Dependabot for version upodates and security updates, as that's more widely used for open source software.

Adding Dependabot's version updating capabilities is done in a separate PR.

Part of #312.

### CODE REVIEW

**Review by zalgonoise — APPROVED** [review]
LGTM

**Comment by MarvinJWendt** [comment]
Since renovate is not running as a GitHub Action / Workflow, I think it might be installed as an app. If that's the case, I am not sure if removing the config will completely disable the bot, or if it will fall back to a default config then. If it's enabled orga-wide we could disable it here with `{ "enabled": false }` in the config, or maybe @patrick246 can uninstall the App / revoke permissions for this repository.

@patrick246 could you check, if renovate is installed as an app?

**Comment by MarvinJWendt** [comment]
PS: We also need to close all RenovateBot PRs after this is merged, so that Dependabot can take over from here.

**Comment by patrick246** [comment]
Yes, renovate was installed as an App, I have revoked permissions on this repository

**Pull request merged**
